"""empty message

Revision ID: 45b9700bc8c6
Revises: None
Create Date: 2016-03-11 01:01:38.971065

"""

# revision identifiers, used by Alembic.
revision = '45b9700bc8c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('login', sa.String(length=15), nullable=True),
    sa.Column('clave', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=20), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_login'), 'usuario', ['login'], unique=True)
    op.create_table('member_to_group',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['usuario.id'], )
    )
    op.create_table('pagina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('pagina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pagina_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagina_titulo'), 'pagina', ['titulo'], unique=True)
    op.create_table('user_to_user',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['usuario.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_user')
    op.drop_index(op.f('ix_pagina_titulo'), table_name='pagina')
    op.drop_table('pagina')
    op.drop_table('member_to_group')
    op.drop_index(op.f('ix_usuario_login'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('mensaje')
    op.drop_table('grupo')
    ### end Alembic commands ###
