"""empty message

Revision ID: 90bce376133a
Revises: None
Create Date: 2016-02-14 13:26:29.494452

"""

# revision identifiers, used by Alembic.
revision = '90bce376133a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('login', sa.String(length=15), nullable=True),
    sa.Column('clave', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_index(op.f('ix_usuario_login'), 'usuario', ['login'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_login'), table_name='usuario')
    op.drop_table('usuario')
    ### end Alembic commands ###
