"""empty message

Revision ID: a87b8dc08eee
Revises: 90bce376133a
Create Date: 2016-02-14 17:51:42.452879

"""

# revision identifiers, used by Alembic.
revision = 'a87b8dc08eee'
down_revision = '90bce376133a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagina',
    sa.Column('idPagina', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPagina')
    )
    op.create_index(op.f('ix_pagina_titulo'), 'pagina', ['titulo'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagina_titulo'), table_name='pagina')
    op.drop_table('pagina')
    ### end Alembic commands ###
